### ISSUE TITLE
Enable Atom feeds

### ISSUE THREAD

**Issue by ewired** [tinytoolkit/tinytoolk.it#7]
I attempted to get the site built locally to enable feeds in Zola as described here: https://www.getzola.org/documentation/templates/feeds/

I ran into an issue, though I made sure I had git-lfs and the submodules set up, I still can't get the site building locally:
```
Building site...
Error: Failed to serve the site
Error: Failed to render content of /path/tinytoolk.it/content/tools/third_hand.md
Error: Reason: Failed to render figure shortcode
Error: Reason: Failed to render 'shortcodes/figure.html'
Error: Reason: Function call 'resize_image' failed
Error: Reason: `resize_image`: Failed to read image: /path/tinytoolk.it/content/tools/third_hand.jpg
```

Ultimately my goal is to have feeds enabled on this site because I would love to see new entries.

**Comment by equinoxefr** [comment]
Same issue for me. Before `git clone` don't forget to run a `git lfs install` only the first time you want to clone an lfs repo.
